<!-- Start Right Navigation Here -->

    </td><td width="125" valign="top"><table border="0" width="125" cellspacing="0" cellpadding="0">
      <tr>
        <td width="125">
            <table border="0" width="100%" cellspacing="0" cellpadding="2">
              <tr>
                <td bgcolor="%%colorcode%%" class="boxborder"><font face="Verdana, Arial" size="2" color="#000000">&nbsp;Special
                  Buys</font></td>
                  <tr><td>&nbsp;
                  </td></tr>
              </tr>
%%specials%%
            </table>
          </td>
      </tr>
    </table></td>

<!-- End Right Navigation Here -->

  </tr>
</table>

<!--End Body Here-->

<!--Start Footer Here-->

<table border="0" width="100%" cellspacing="0" cellpadding="0">
  <tr bgcolor="#000000" height="19">
    <td align="left">&nbsp;</td>
    <td align="right">&nbsp;</td>
  </tr>
</table>
<br>
<table border="0" width="100%" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center"><font face="Verdana, Arial" size="1">&copy; 2000 %%mername%%
      All Rights Reserved<br>
      &nbsp;<br>
      
<!-- Please leave the comment below intact -->

      FREE Shopping Cart Provided by <a href="http://www.merchant-store.com" target="_blank"><font color="#CC0000">merchant-store.com</font></a></font><BR>
      <BR></td>
  </tr>
</table>

<!--End Footer Here-->









</body>
</html>